### ISSUE TITLE
Style issue with search in Repo

### ISSUE THREAD

**Issue by theobouwman** [DennisSnijder/MakeGithubGreatAgain#40] opened 2017-02-14 20:48 UTC
<img width="1023" alt="schermafbeelding 2017-02-14 om 21 46 47" src="https://cloud.githubusercontent.com/assets/16098190/22948550/3d70df38-f2ff-11e6-9ca3-76374cbe5957.png">

Element's style left of the input box is broken.

**Comment by jackwilsdon** [comment] 2017-02-14 20:49
Does #38 not fix this? Duplicate of #36 too.

**Closed** 2017-02-14 20:50 UTC
